name: git_conventional_commit
description: Simple command for create your conventional commits
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  args: ^2.4.2
  cli_menu: ^0.4.0+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
